## 第五章pandas入门

   ### pandas是贯穿本书后续部分的主要工具，包含数据结构和数据处理工具的设计是的在python中进行数据清洗和分析十分快捷， 主要用于处理表格型货异质型数据，numpy则主要处理同质行的数值类数组数据

In [1]:
import pandas as pd

### 导入常用的类series和dataframe

In [2]:
from pandas import Series, DataFrame   

### series是一种以为的数组型对象，包含了一个值序列并且包含了数据标签

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index # 与 range(4)类似

RangeIndex(start=0, stop=4, step=1)

In [11]:
obj2 = pd.Series([4, 7, 3, -4], index = ['d', 'b', 'a', 'c'])

In [12]:
obj2

d    4
b    7
a    3
c   -4
dtype: int64

In [13]:
obj2 .index

Index(['d', 'b', 'a', 'c'], dtype='object')

可以从数据中选择数据时使用标签来进行索引

In [14]:
obj2['a']

3

In [15]:
obj2[obj2 > 0]

d    4
b    7
a    3
dtype: int64

In [16]:
obj2*2

d     8
b    14
a     6
c    -8
dtype: int64

In [18]:
import numpy as np

In [19]:
np.exp(obj2)

d      54.598150
b    1096.633158
a      20.085537
c       0.018316
dtype: float64

### 从另外一个角度可以把series看作是长度固定且有序的字典，它可以将索引值和数据值按位置配对，可以使用使用字典的上下文中，也可以使用series

In [20]:
'b' in obj2

True

In [22]:
"e" in obj2

False

In [23]:
sdata= {'dddd': 25000, 'teax':72000, 'oregon':16000, 'utah':5000}

In [24]:
obj3= pd.Series(sdata)

In [25]:
obj3

dddd      25000
teax      72000
oregon    16000
utah       5000
dtype: int64

In [30]:
states = ['california', 'ohio','oregon','texas']

In [31]:
obj4 = pd.Series(sdata, index=states)

In [32]:
obj4

california        NaN
ohio              NaN
oregon        16000.0
texas             NaN
dtype: float64

### pandas 使用isnull 和notnull函数来检查缺失数据

In [33]:
pd.isnull(obj4)

california     True
ohio           True
oregon        False
texas          True
dtype: bool

In [34]:
pd.notnull(obj4)

california    False
ohio          False
oregon         True
texas         False
dtype: bool

In [35]:
obj4.isnull()

california     True
ohio           True
oregon        False
texas          True
dtype: bool

In [36]:
obj4

california        NaN
ohio              NaN
oregon        16000.0
texas             NaN
dtype: float64

In [37]:
obj4.name = 'population'

In [38]:
obj4.index.name = "state"

In [39]:
obj4

state
california        NaN
ohio              NaN
oregon        16000.0
texas             NaN
Name: population, dtype: float64

In [40]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [41]:
obj.index = ['bob','steve','jeff','Ryan']

In [42]:
obj

bob      4
steve    7
jeff    -5
Ryan     3
dtype: int64

## DataFrame 表格型数据结构，含有一组有序的列，每个列是不同的值类型，既有行索引也有列索引

In [45]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada','Nevada'],
       'year':[2000, 2001, 2002, 2001, 2002,2003],
       'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [46]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

### 当使用jupyter notebook ，pandas dataframe对象会以对浏览器友好的HTML表格的方式呈现

In [47]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

### 如果指定了列序列，则dataframe的列就会按照指定顺序进行排列

In [49]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [60]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
....: 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [61]:
frame3 = pd.DataFrame(pop)

In [62]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [63]:
frame3 = pd.DataFrame(pop)

In [64]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [67]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

可以使用.T对dataframe进行转置

In [69]:
pd.DataFrame(pop, index=[2001,2002,2003])

AttributeError: 'list' object has no attribute 'astype'

### pandas索引对象负责管理轴标签和其他元数据

In [71]:
obj = pd.Series(range(3),index= ['a', 'b','c'])

In [72]:
index = obj.index

In [73]:
index

Index(['a', 'b', 'c'], dtype='object')

In [75]:
index[1:]

Index(['b', 'c'], dtype='object')

index对象是不可变的，因此用户不能对其进行修改

In [81]:
labels= pd.Index(np.arange(3))

In [82]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [84]:
obj2 = pd.Series([1.3, -2.5, 0], index=labels)

In [85]:
obj2

0    1.3
1   -2.5
2    0.0
dtype: float64

In [86]:
obj2.index is labels

True

In [87]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [88]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [89]:
'Ohio' in frame3.columns

True

### 与python 的集合不同，pandas的Index可以包含重复的标签：

In [90]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [91]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 基本功能   

### 重新索引

In [92]:
obj = pd.Series([4.5,7.2, -5.3,3.6], index = ['d','b', 'a', 'c'])

In [93]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

### 使用Series的reindex将会根据新索引进行重排，如果某个索引值当前不存在，就引入缺失值

In [94]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [95]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [96]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [97]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [98]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

使用ffill可以实现向前值填充：

In [100]:
 obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [102]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
....: index=['a', 'c', 'd'],
....: columns=['Ohio', 'Texas','California'])

In [103]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [104]:
frame2 = frame.reindex(['a', 'b','c', 'd'])

In [105]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

#### 列可以用columns关键字重新索引

In [106]:
states = ['Texas', 'Utah', 'California']

In [107]:
frame.reindex(columns= states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### 索引 选取 过滤

In [109]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [110]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [111]:
obj['b']

1.0

In [112]:
obj[1]

1.0

In [113]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [114]:
obj[['b','a','c']]

b    1.0
a    0.0
c    2.0
dtype: float64

利用标签的切片运算与普通的python切片运算不同，其末端是包含的：

In [115]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [117]:
data.loc['Colorado', ['two', 'three']]

AttributeError: 'dict' object has no attribute 'loc'

### 算术运算和数据对齐

In [3]:
import pandas as pd

In [7]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])

In [9]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
.....:   index= ['a', 'c', 'e', 'f', 'g'])

In [10]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [11]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [12]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

#### 相加的时候 自动的数据对齐操作在不重叠的索引处引入了NA值，缺失值会在算术过程中传播

In [18]:
import numpy as np

In [19]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),columns=list('bcd'),
.....:     index=['Ohio', 'Texas', 'Colorado'])

In [20]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list('bde'),
.....: index=['Utah', 'Ohio', 'Texas','Oregon'])

In [21]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [22]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [23]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [24]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
.....: columns=list('abcd'))

In [25]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
.....: columns=list('abcde'))

In [26]:
df2.loc[1, 'b'] = np.nan

In [27]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [28]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [29]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

#### 使用DF1的add方法，传入DF2以及一个fill-value参数：

In [30]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

### dataframe和series之间的运算

In [31]:
arr = np.arange(12.).reshape((3, 4))

In [32]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [33]:
arr[0]

array([0., 1., 2., 3.])

In [34]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

###  函数应用和映射   numpy的ufuncs可以用于操作pandas对象：

In [36]:
frame = pd.DataFrame(np.random.randn(4, 3),columns=list('bde'),
.....: index=['Utah', 'Ohio', 'Texas','Oregon'])

In [37]:
frame

b         d         e
Utah   -1.534879  0.712773 -0.948722
Ohio    0.677887 -1.266404 -1.630728
Texas  -0.442220  0.353627 -1.652504
Oregon  0.196569 -0.185856 -0.398415

In [38]:
 np.abs(frame)

b         d         e
Utah    1.534879  0.712773  0.948722
Ohio    0.677887  1.266404  1.630728
Texas   0.442220  0.353627  1.652504
Oregon  0.196569  0.185856  0.398415

numpy的绝对值操作

In [39]:
f = lambda x: x.max() - x.min()

In [40]:
frame.apply(f)

b    2.212766
d    1.979177
e    1.254089
dtype: float64

这里的f计算了series的最大值和最小值的差，在frame的每列都执行了一次

In [41]:
frame.apply(f, axis='columns')

Utah      2.247652
Ohio      2.308615
Texas     2.006131
Oregon    0.594984
dtype: float64

IndentationError: expected an indented block (<ipython-input-42-02addc859110>, line 2)

### 排序和排名

In [43]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [45]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [46]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
.....: index=['three', 'one'],
.....: columns=['d', 'a', 'b', 'c'])

In [47]:
 frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [48]:
 df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
.....: [np.nan, np.nan], [0.75, -1.3]],
.....: index=['a', 'b', 'c', 'd'],
.....: columns=['one', 'two'])

In [50]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

### 唯一值 值计数 成员资格

In [54]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c','c'])

In [55]:
uniques = obj.unique()

In [56]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [58]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
.....: 'Qu2': [2, 3, 1, 2, 3],
.....: 'Qu3': [1, 5, 2, 4, 4]})

In [59]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [60]:
 result = data.apply(pd.value_counts).fillna(0)

In [61]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

#  数据加载 存储 与文件格式

#### 访问数据是使用本书所介绍的这些工具的第一步，这里介绍pandas的数据输入与输出，输入输出通常可以划分为几个大类：读取文本文件和其他更高效的磁盘存储格式，加载数据库中的数据，利用Web API操作网络资源。

In [68]:
import json

In [69]:
obj = """
{"name": "Wes",
"places_lived": ["United States", "Spain", "Germany"],
"pet": null,
"siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
{"name": "Katie", "age": 38,
"pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [70]:
result = json.loads(obj)

In [71]:
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [72]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])

In [73]:
siblings

name  age
0  Scott   30
1  Katie   38

In [77]:
tables= pd.DataFrame(result['siblings'], columns=['name', 'age'])

In [80]:
len(tables)

2

In [81]:
failures = tables[0]

KeyError: 0

In [83]:
frame = pd.read_csv('examples/ex1.csv')

FileNotFoundError: File b'examples/ex1.csv' does not exist

In [84]:
frame = pd.DataFrame({'a': np.random.randn(100)})

In [85]:
store = pd.HDFStore('mydata.h5')

In [86]:
store['obj1'] = frame

In [87]:
store['obj1_col'] = frame['a']

In [88]:
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5